package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"

	"github.com/wricardo/drbrain-motor-programming/game/service"
	"github.com/wricardo/drbrain-motor-programming/graph/generated"
	"github.com/wricardo/drbrain-motor-programming/graph/model"
	"github.com/wricardo/drbrain-motor-programming/validate"
)

// CreateSession is the resolver for the createSession field.
func (r *mutationResolver) CreateSession(ctx context.Context, mapID string, displayName *string) (*model.Session, error) {
	name := ""
	if displayName != nil {
		name = *displayName
	}
	s, err := r.Service.CreateSession(mapID, name)
	if err != nil {
		return nil, toGQLError(err)
	}
	return toSession(s), nil
}

// DeleteSession is the resolver for the deleteSession field.
func (r *mutationResolver) DeleteSession(ctx context.Context, id string) (bool, error) {
	if err := r.Service.DeleteSession(id); err != nil {
		return false, toGQLError(err)
	}
	return true, nil
}

// RenameSession is the resolver for the renameSession field.
func (r *mutationResolver) RenameSession(ctx context.Context, id string, displayName string) (*model.Session, error) {
	s, err := r.Service.RenameSession(id, displayName)
	if err != nil {
		return nil, toGQLError(err)
	}
	return toSession(s), nil
}

// SetProgram is the resolver for the setProgram field.
func (r *mutationResolver) SetProgram(ctx context.Context, sessionID string, program model.ProgramInput) (*model.Session, error) {
	s, err := r.Service.SetProgram(sessionID, fromProgramInput(program))
	if err != nil {
		return nil, toGQLError(err)
	}
	return toSession(s), nil
}

// Run is the resolver for the run field.
func (r *mutationResolver) Run(ctx context.Context, sessionID string, speedMs *int) (*model.Session, error) {
	speed := 500
	if speedMs != nil {
		speed = *speedMs
	}
	s, err := r.Service.Run(sessionID, speed)
	if err != nil {
		return nil, toGQLError(err)
	}
	return toSession(s), nil
}

// Pause is the resolver for the pause field.
func (r *mutationResolver) Pause(ctx context.Context, sessionID string) (*model.Session, error) {
	s, err := r.Service.Pause(sessionID)
	if err != nil {
		return nil, toGQLError(err)
	}
	return toSession(s), nil
}

// Step is the resolver for the step field.
func (r *mutationResolver) Step(ctx context.Context, sessionID string) (*model.Session, error) {
	s, err := r.Service.Step(sessionID)
	if err != nil {
		return nil, toGQLError(err)
	}
	return toSession(s), nil
}

// Reset is the resolver for the reset field.
func (r *mutationResolver) Reset(ctx context.Context, sessionID string) (*model.Session, error) {
	s, err := r.Service.Reset(sessionID)
	if err != nil {
		return nil, toGQLError(err)
	}
	return toSession(s), nil
}

// CreateMap is the resolver for the createMap field.
func (r *mutationResolver) CreateMap(ctx context.Context, mapArg model.MapInput) (*model.Map, error) {
	if err := checkAdminKey(ctx); err != nil {
		return nil, err
	}
	m, err := r.Service.CreateMap(fromMapInput(mapArg))
	if err != nil {
		return nil, toGQLError(err)
	}
	return toMap(m), nil
}

// UpdateMap is the resolver for the updateMap field.
func (r *mutationResolver) UpdateMap(ctx context.Context, mapArg model.MapInput) (*model.Map, error) {
	if err := checkAdminKey(ctx); err != nil {
		return nil, err
	}
	if _, err := r.Service.GetMap(mapArg.ID); err != nil {
		return nil, toGQLError(err)
	}
	m, err := r.Service.SaveMap(fromMapInput(mapArg))
	if err != nil {
		return nil, toGQLError(err)
	}
	return toMap(m), nil
}

// DeleteMap is the resolver for the deleteMap field.
func (r *mutationResolver) DeleteMap(ctx context.Context, id string) (bool, error) {
	if err := checkAdminKey(ctx); err != nil {
		return false, err
	}
	if err := r.Service.DeleteMap(id); err != nil {
		return false, toGQLError(err)
	}
	return true, nil
}

// ValidateMap is the resolver for the validateMap field.
func (r *mutationResolver) ValidateMap(ctx context.Context, mapArg model.MapInput) (*model.MapValidationResult, error) {
	if err := checkAdminKey(ctx); err != nil {
		return nil, err
	}
	res := validate.Check(fromMapInput(mapArg))
	out := &model.MapValidationResult{
		Valid:             res.Valid,
		Issues:            make([]*model.MapValidationIssue, len(res.Issues)),
		UnreachableTreats: toPositions(res.UnreachableTreats),
	}
	for i, msg := range res.Issues {
		out.Issues[i] = &model.MapValidationIssue{Message: msg}
	}
	return out, nil
}

// Maps is the resolver for the maps field.
func (r *queryResolver) Maps(ctx context.Context) ([]*model.Map, error) {
	return toMaps(r.Service.ListMaps()), nil
}

// Map is the resolver for the map field.
func (r *queryResolver) Map(ctx context.Context, id string) (*model.Map, error) {
	m, err := r.Service.GetMap(id)
	if err != nil {
		if isNotFound(err) {
			return nil, nil
		}
		return nil, toGQLError(err)
	}
	return toMap(m), nil
}

// Session is the resolver for the session field.
func (r *queryResolver) Session(ctx context.Context, id string) (*model.Session, error) {
	s, err := r.Service.GetSession(id)
	if err != nil {
		if isNotFound(err) {
			return nil, nil
		}
		return nil, toGQLError(err)
	}
	return toSession(s), nil
}

// Sessions is the resolver for the sessions field.
func (r *queryResolver) Sessions(ctx context.Context, sort *model.SessionSort, limit *int, mapID *string) ([]*model.Session, error) {
	f := service.SessionFilter{Sort: "recent"}
	if sort != nil && *sort == model.SessionSortCreated {
		f.Sort = "created"
	}
	if limit != nil {
		f.Limit = *limit
	}
	if mapID != nil {
		f.MapID = *mapID
	}
	list, err := r.Service.ListSessions(f)
	if err != nil {
		return nil, toGQLError(err)
	}
	out := make([]*model.Session, len(list))
	for i, s := range list {
		out[i] = toSession(s)
	}
	return out, nil
}

// SessionUpdated is the resolver for the sessionUpdated field. It subscribes
// before reading the snapshot so no update is lost between the two, emits the
// snapshot immediately, then forwards hub updates.
func (r *subscriptionResolver) SessionUpdated(ctx context.Context, sessionID string) (<-chan *model.SessionUpdate, error) {
	updates := r.Hub.SubscribeSession(ctx, sessionID)
	s, err := r.Service.GetSession(sessionID)
	if err != nil {
		return nil, toGQLError(err)
	}
	return forwardSessionUpdates(ctx, s, updates, subscriptionBuffer), nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
