// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type Frame struct {
	// Tape index; -1 is the main tape.
	Tape int `json:"tape"`
	// Index of the next instruction to run on that tape.
	Pc int `json:"pc"`
}

type Map struct {
	ID             string      `json:"id"`
	Name           string      `json:"name"`
	Description    string      `json:"description"`
	Difficulty     string      `json:"difficulty"`
	Width          int         `json:"width"`
	Height         int         `json:"height"`
	Layout         []string    `json:"layout"`
	Start          *Position   `json:"start"`
	StartFacing    Facing      `json:"startFacing"`
	Rocks          []*Position `json:"rocks"`
	Treats         []*Position `json:"treats"`
	MainTapeLength int         `json:"mainTapeLength"`
	SubTapeLengths []int       `json:"subTapeLengths"`
	MaxSteps       int         `json:"maxSteps"`
	MaxCallDepth   int         `json:"maxCallDepth"`
	AllowRecursion bool        `json:"allowRecursion"`
}

type MapInput struct {
	ID             string   `json:"id"`
	Name           string   `json:"name"`
	Description    *string  `json:"description,omitempty"`
	Difficulty     *string  `json:"difficulty,omitempty"`
	Layout         []string `json:"layout"`
	MainTapeLength *int     `json:"mainTapeLength,omitempty"`
	SubTapeLengths []int    `json:"subTapeLengths,omitempty"`
	MaxSteps       *int     `json:"maxSteps,omitempty"`
	MaxCallDepth   *int     `json:"maxCallDepth,omitempty"`
	AllowRecursion *bool    `json:"allowRecursion,omitempty"`
}

type MapValidationIssue struct {
	Message string `json:"message"`
}

type MapValidationResult struct {
	Valid  bool                  `json:"valid"`
	Issues []*MapValidationIssue `json:"issues"`
	// Cells reachable check result: treats unreachable from start.
	UnreachableTreats []*Position `json:"unreachableTreats"`
}

type Mutation struct {
}

type Position struct {
	X int `json:"x"`
	Y int `json:"y"`
}

type Program struct {
	Main []Instruction   `json:"main"`
	Subs [][]Instruction `json:"subs"`
}

type ProgramInput struct {
	Main []Instruction   `json:"main"`
	Subs [][]Instruction `json:"subs"`
}

type Query struct {
}

type Session struct {
	ID          string `json:"id"`
	DisplayName string `json:"displayName"`
	MapID       string `json:"mapId"`
	// Snapshot of the map taken when the session was created.
	Map     *Map     `json:"map"`
	Program *Program `json:"program"`
	VM      *VMState `json:"vm"`
	Playing bool     `json:"playing"`
	SpeedMs int      `json:"speedMs"`
	// Increments on every state change; clients ignore updates with seq <= last seen.
	Seq          int        `json:"seq"`
	CreatedAt    time.Time  `json:"createdAt"`
	LastActionAt time.Time  `json:"lastActionAt"`
	Attempts     int        `json:"attempts"`
	BestSteps    *int       `json:"bestSteps,omitempty"`
	LastEvent    *StepEvent `json:"lastEvent,omitempty"`
}

type SessionUpdate struct {
	Seq     int        `json:"seq"`
	Session *Session   `json:"session"`
	Event   *StepEvent `json:"event,omitempty"`
}

type SimulationResult struct {
	Status     Status       `json:"status"`
	LossReason *LossReason  `json:"lossReason,omitempty"`
	Steps      int          `json:"steps"`
	FinalState *VMState     `json:"finalState"`
	Events     []*StepEvent `json:"events,omitempty"`
}

type StepEvent struct {
	Step         int         `json:"step"`
	Instruction  Instruction `json:"instruction"`
	TapeIndex    int         `json:"tapeIndex"`
	SlotIndex    int         `json:"slotIndex"`
	From         *Position   `json:"from"`
	To           *Position   `json:"to"`
	FacingBefore Facing      `json:"facingBefore"`
	FacingAfter  Facing      `json:"facingAfter"`
	Blocked      bool        `json:"blocked"`
	Collected    *Position   `json:"collected,omitempty"`
	CallStack    []*Frame    `json:"callStack"`
	Status       Status      `json:"status"`
	LossReason   *LossReason `json:"lossReason,omitempty"`
}

type Subscription struct {
}

type VMState struct {
	Pos             *Position   `json:"pos"`
	Facing          Facing      `json:"facing"`
	TreatsRemaining []*Position `json:"treatsRemaining"`
	// Bottom frame is main; the last frame is the active tape.
	CallStack  []*Frame    `json:"callStack"`
	Steps      int         `json:"steps"`
	Status     Status      `json:"status"`
	LossReason *LossReason `json:"lossReason,omitempty"`
	Visited    []*Position `json:"visited"`
}

type Facing string

const (
	FacingUp    Facing = "UP"
	FacingRight Facing = "RIGHT"
	FacingDown  Facing = "DOWN"
	FacingLeft  Facing = "LEFT"
)

var AllFacing = []Facing{
	FacingUp,
	FacingRight,
	FacingDown,
	FacingLeft,
}

func (e Facing) IsValid() bool {
	switch e {
	case FacingUp, FacingRight, FacingDown, FacingLeft:
		return true
	}
	return false
}

func (e Facing) String() string {
	return string(e)
}

func (e *Facing) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Facing(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Facing", str)
	}
	return nil
}

func (e Facing) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Facing) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Facing) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Instruction string

const (
	InstructionEmpty       Instruction = "EMPTY"
	InstructionTurnLeft    Instruction = "TURN_LEFT"
	InstructionTurnRight   Instruction = "TURN_RIGHT"
	InstructionMoveForward Instruction = "MOVE_FORWARD"
	InstructionCallSub1    Instruction = "CALL_SUB_1"
	InstructionCallSub2    Instruction = "CALL_SUB_2"
	InstructionCallSub3    Instruction = "CALL_SUB_3"
)

var AllInstruction = []Instruction{
	InstructionEmpty,
	InstructionTurnLeft,
	InstructionTurnRight,
	InstructionMoveForward,
	InstructionCallSub1,
	InstructionCallSub2,
	InstructionCallSub3,
}

func (e Instruction) IsValid() bool {
	switch e {
	case InstructionEmpty, InstructionTurnLeft, InstructionTurnRight, InstructionMoveForward, InstructionCallSub1, InstructionCallSub2, InstructionCallSub3:
		return true
	}
	return false
}

func (e Instruction) String() string {
	return string(e)
}

func (e *Instruction) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Instruction(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Instruction", str)
	}
	return nil
}

func (e Instruction) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Instruction) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Instruction) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type LossReason string

const (
	LossReasonStepLimit    LossReason = "STEP_LIMIT"
	LossReasonCallDepth    LossReason = "CALL_DEPTH"
	LossReasonProgramEnded LossReason = "PROGRAM_ENDED"
)

var AllLossReason = []LossReason{
	LossReasonStepLimit,
	LossReasonCallDepth,
	LossReasonProgramEnded,
}

func (e LossReason) IsValid() bool {
	switch e {
	case LossReasonStepLimit, LossReasonCallDepth, LossReasonProgramEnded:
		return true
	}
	return false
}

func (e LossReason) String() string {
	return string(e)
}

func (e *LossReason) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = LossReason(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid LossReason", str)
	}
	return nil
}

func (e LossReason) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *LossReason) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e LossReason) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SessionSort string

const (
	SessionSortRecent  SessionSort = "RECENT"
	SessionSortCreated SessionSort = "CREATED"
)

var AllSessionSort = []SessionSort{
	SessionSortRecent,
	SessionSortCreated,
}

func (e SessionSort) IsValid() bool {
	switch e {
	case SessionSortRecent, SessionSortCreated:
		return true
	}
	return false
}

func (e SessionSort) String() string {
	return string(e)
}

func (e *SessionSort) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SessionSort(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SessionSort", str)
	}
	return nil
}

func (e SessionSort) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SessionSort) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SessionSort) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Status string

const (
	StatusReady   Status = "READY"
	StatusRunning Status = "RUNNING"
	StatusWon     Status = "WON"
	StatusLost    Status = "LOST"
)

var AllStatus = []Status{
	StatusReady,
	StatusRunning,
	StatusWon,
	StatusLost,
}

func (e Status) IsValid() bool {
	switch e {
	case StatusReady, StatusRunning, StatusWon, StatusLost:
		return true
	}
	return false
}

func (e Status) String() string {
	return string(e)
}

func (e *Status) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Status(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Status", str)
	}
	return nil
}

func (e Status) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Status) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Status) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
